[DEFAULT]
PAGE_TITLE = LangGraph: Chatbot feel free to communicate
LLM_OPTIONS = GROQ,OPENAI,GEMINI
USE_CASE_OPTIONS = Basic Chatbot,Chatbot with tool,AI News,Blog generator
TOOLS= Tavily,Sql
GROQ = llama-3.1-8b-instant,openai/gpt-oss-120b,qwen/qwen3-32b,meta-llama/llama-4-scout-17b-16e-instruct
; OPENAI = llama-3.1-8b-instant, openai/gpt-oss-120b, qwen/qwen3-32b, meta-llama/llama-4-scout-17b-16e-instruct
; GEMINI = llama-3.1-8b-instant, openai/gpt-oss-120b, qwen/qwen3-32b, meta-llama/llama-4-scout-17b-16e-instruct
